App\Entity\Address:
  attributes:
    security: 'is_granted("ROLE_USER")'
  collectionOperations:
    get:
      security: 'is_granted("ROLE_ADMIN")'
    post:
      security: 'is_granted("ROLE_USER")'
  itemOperations:
    get:
      security: 'is_granted("ROLE_USER") and object.getUser().getId() == user.getId()'
    patch:
      security: 'is_granted("ROLE_USER") and object.getUser().getId() == user.getId()'
    delete: ~
