App\Entity\BasketLine:
  collectionOperations:
    post:
      method: 'POST'
      path: '/basket-lines'
      controller: 'App\Controller\Basket\CreateBasketLine'
  itemOperations:
    get:
      formats:
        0: 'json'
    patch:
      security: 'is_granted("ROLE_USER") and object.getBasket().getUser().getId() == user.getId()'
    delete:
      security: 'is_granted("ROLE_USER") and object.getBasket().getUser().getId() == user.getId()'

