App\Entity\Category:
  attributes:
    normalization_context:
      groups: ['categories']
  collectionOperations:
    get:
      formats:
        0: 'json'
    post:
      security: 'is_granted("ROLE_ADMIN")'
  itemOperations:
    get: ~
    patch:
      security: 'is_granted("ROLE_ADMIN")'
    delete:
      security: 'is_granted("ROLE_ADMIN")'
