App\Entity\Product:
  collectionOperations:
    get_products:
      method: 'GET'
      path: '/products'
      controller: 'App\Controller\Getters\GetProducts'
      pagination_fetch_join_collection: true
      normalization_context:
        groups: ['product']
    post:
      security: 'is_granted("ROLE_ADMIN")'
  itemOperations:
    get: ~
    patch:
      security: 'is_granted("ROLE_ADMIN")'
    delete:
      security: 'is_granted("ROLE_ADMIN")'
