App\Entity\Product:
  collectionOperations:
    get_products:
      method: 'GET'
      path: '/products'
      controller: 'App\Controller\Getters\GetProducts'
      pagination_fetch_join_collection: true
      normalization_context:
        groups: ['products']
    get_new_products:
      method: 'GET'
      path: '/products/news'
      controller: 'App\Controller\Getters\GetNewProducts'
      pagination_fetch_join_collection: true
      normalization_context:
        groups: ['products']
      formats:
        0: 'json'
    post:
      security: 'is_granted("ROLE_ADMIN")'
  itemOperations:
    get:
      normalization_context:
        groups: ['products', 'product']
      formats:
        0: 'json'
    patch:
      security: 'is_granted("ROLE_ADMIN")'
    delete:
      security: 'is_granted("ROLE_ADMIN")'
