App\Entity\User:
  collectionOperations:
    get:
      security: 'is_granted("ROLE_ADMIN")'
      normalization_context:
        groups: ['getUser']
    create_user:
      method: 'POST'
      path: '/create_user'
      controller: 'App\Controller\CreateUser'
      normalization_context:
        groups: ['getUser']
  itemOperations:
    get:
      security: 'is_granted("ROLE_ADMIN") or object.getId() == user.getId()'
      normalization_context:
        groups: ['getUser']
      formats:
        0: 'json'
    update_user:
      security: 'is_granted("ROLE_USER") and object.getId() == user.getId()'
      method: 'PATCH'
      path: '/users/{id}'
      controller: 'App\Controller\UpdateUser'
      normalization_context:
        groups: ['getUser']

