easy_admin:
  formats:
    date:     'd/m/y'
    time:     'H:i'
    datetime: 'd/m/y H:i'
  site_name: "Renarou"
  design:
    brand_color: '#FF7400'
    menu:
      - label: 'Produits'
        children: [
          { entity: 'Product', label: 'Produits' },
          { entity: 'Reference', label: 'Références' },
          { entity: 'Size', label: 'Tailles' }
          { entity: 'Image', label: 'Images' }
        ]
      - label: 'Catégories'
        children: [
          { entity: 'Category', label: 'Catégories' },
          { entity: 'SubCategory', label: 'Sous-catégories' },
        ]
      - label: 'Utilisateurs'
        children: [
          { entity: 'User', label: 'Utilisateurs' },
          { entity: 'Address', label: 'Adresses' },
        ]
      - { entity: 'Banner', label: 'Bannières' }
      - label: 'Commandes'
        children: [
          { entity: 'Commande', label: 'Commandes' },
          { entity: 'Delivery', label: 'Mode de livraison' },
        ]
      - { entity: 'DiscountCode', label: 'Codes promo' }
